# Generated by Django 5.2.9 on 2025-12-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temp_f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.room')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
