# Generated by Django 5.2.9 on 2025-12-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_reading_room_monitor_reading_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='monitor_id',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='monitor',
        ),
        # Add a nullable identifier field first (no uniqueness enforced yet).
        # We'll populate it in a subsequent data migration and then enforce constraints.
        migrations.AddField(
            model_name='monitor',
            name='identifier',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.room'),
        ),
    ]
