# Generated by Django 5.2.9 on 2025-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_populate_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
