# Generated by Django 5.2.9 on 2025-12-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_room_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='patient_name',
        ),
        migrations.AlterField(
            model_name='reading',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.room'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='monitor.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'room')},
            },
        ),
        migrations.AddField(
            model_name='reading',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.patient'),
        ),
    ]
