# Generated by Django 5.2.9 on 2025-12-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_room_patient_name_alter_reading_room_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='monitor.patient'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.room'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room',
        ),
    ]
