# Generated by Django 6.0.3 on 2026-03-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_patient_options_alter_patient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='monitor.room'),
        ),
    ]
