# Generated by Django 6.0.3 on 2026-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_monitor_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
