# Generated by Django 6.0.3 on 2026-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_reading_spo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
